apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: py4svc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py4svc 
  name: py4svc
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: py4svc
    weight: 100 
